### ISSUE TITLE
Error: Cork buffer must not be acquired without checking canCork!

### ISSUE THREAD

**Issue by Ma5t3rful** [mmertama/Gempyre#11]
This error occurs randomly. mostly with with heavier apps like Tilze example. I think this is a problem with uWebsockets and multi-threading. See [this](https://github.com/uNetworking/uWebSockets/blob/master/misc/READMORE.md#threading).

**Comment by mmertama** [comment]
uWebSocket has been quite unpleasant library to use - and it is more engine for its JS wrapper, it  requires uSocket and UVLib that floods tons of warning. I was about to change that to libwebsocket, but late versions wont compile with clang - therefore Im considering WebSocket++ as transport backend and hence to interested to fight more with these uwebsocket issues.  However I may know why this issue occurs and I will look if I find a neat solution.

**Comment by mmertama** [comment]
There is a quick fix in 'deferred_send' branch - but it looks pretty slow. I have to look it further.

**Comment by mmertama** [comment]
A branch where that is fixed is in master - about 20x speed improvement over earlier 'fix' - about 4x speed improvement over any ealier version :-D (measured with fire example)
