### ISSUE TITLE
Request for an ARCHITECTURE.md

### ISSUE THREAD

**Issue by elankath** [mmertama/Gempyre#14]
Apologies if this is already answered somewhere - I couldn't find a FAQ. What is the architecture of Gempyre ? Is it like [Tauri](https://tauri.app/) - a framework that  leverages the OS native webview ? Or does it bundle its own HTML/CSS renderer like [Sciter](https://github.com/c-smile/sciter-sdk) ?

**Comment by mmertama** [comment]
In README.md there is short FAQ  but it may no answer to your question. I have drawn some images in the past but really never published any, propably I should. But basically Gempyre application is a webserver and UI can be rendered to any process connecting it. If you look the README (or examples) each UI HTML uses "<script type="text/javascript" src="gempyre.js"></script>" that makes UI to connect to gempyre (application/server).  There are plenty of configuration options what UI to use, the most straightforward (and most cases the fallback) is the system browser, but that lacks File dialogs (and such) so better experience is get using a special UI app - I mostly have used Python/pywebview, but also  Qt/Webview and Hiillos (you find the repo here - I never finalized it as using webview is not very pleasant, and I found pywebview the easiest) - Most of the communication between UI and server is done using websocket (there are few library approaches).  Anyway there is no spesific renderer and hence its up to developer what features to use HTML/CSS/JS - I was planning to combine gempyre with Angular/Vue/React, but never have had time for that - yet I suppose it would be pretty cool way to implement a GUI for a C++ app.

**Comment by elankath** [comment]
Thanks for the detailed explanation. Closing this.
