### ISSUE TITLE
Gempyre binaries use 100% of CPU. + Workaround

### ISSUE THREAD

**Issue by Ma5t3rful** [mmertama/Gempyre#3]
I compiled a simple app + calculator example both of them on Linux use 100% of CPU on one core this shouldn't be normal. also the web browser does not open up as a stand-alone app. it opens up the whole browser.
![](https://s6.uupload.ir/files/screenshot_20221207_202755_dkuy.png)

**Comment by Ma5t3rful** [comment]
Today, I managed to set up a virtual machine to test the library on windows7. Exactly the same problem. One core went up to 100 present. As soon as you launch a Gempyre  app, the cpu fan start screaming.

**Comment by Ma5t3rful** [comment]
To everyone that has this problem: I managed to workaround the issue by adding a tiny bit of delay in `eventloop()`. 
You can clone my fork and re-build the library and install it.

run this command to clone my branch.
`git clone --branch Workaround_Issues https://github.com/Master811129/Gempyre.git`

**Comment by mmertama** [comment]
I added a sleep as a quick fix. I have a pretty good idea how to do a  real fix for the issue. Im planning a big refactoring and will fix that there if not any earlier.

**Comment by Ma5t3rful** [comment]
@mmertama I can confirm that the Issue has been fixed. But does this workaround have any impact on performance? I'm a bit worried about gempyre graphics.

**Comment by mmertama** [comment]
> @mmertama I can confirm that the Issue has been fixed. But does this workaround have any impact on performance? I'm a bit worried about gempyre graphics.

That was a quick workaround and Im on studying way to implement a real fix.

There are also few other performance wise poor solutions that I have to revisit. Rust implementation (gemgui-rs) can do 90fps on my old mac and I would expect that Gempyre should reach the same.
