### ISSUE TITLE
"Gempyre API has few headers (deprecated)?" What does that mean?

### ISSUE THREAD

**Issue by Ma5t3rful** [mmertama/Gempyre#7]
@mmertama 
Please elaborate more about this line in `README` (or here). what should be used instead? should/can i still use gempyre utils' functions?

BTW what does the word "Gempyre" actually mean? looked it up didn't find anything :)

**Comment by mmertama** [comment]
Gempyre means (or should mean) absolutely nothing - I just wanted to have an unique name so it's easier to google.  Deprecated functions are marked as [[deprecated]] - you get noticed when build. The functions shall still work and attribute should tell what to use instead.

**Comment by Ma5t3rful** [comment]
> absolutely nothing - I just wanted to have an unique name so it's easier to google.

Pro move

> Deprecated functions are marked as [[deprecated]] - you get noticed when build. The functions shall still work and attribute should tell what to use instead.

Thanks. Keep up the great work.
