### ISSUE TITLE
closing the tab in browser does not kill the software in the background 

### ISSUE THREAD

**Issue by Ma5t3rful** [mmertama/Gempyre#8]
@mmertama Closing the tab in browser does not kill the software in the background
Steps to reproduce:
1. open `calc` example
2. replace constructor with `Gempyre::Ui ui(Calc_resourceh, "calc.html", "brave", "");//change the name to your browser`
3. close the tab.
4. app won't close.
tried it with Librewolf (a fork of Firefox). Same behavior.

**Comment by Ma5t3rful** [comment]
The previous release didn't have this problem. this problem appeared in `1.0.0`.

**Comment by mmertama** [comment]
There was some regression in 1.0.0 - I just pushed 1.0.1 that fix the issue among others. Please verify if there is still the issue.

**Comment by Ma5t3rful** [comment]
@mmertama It works now.  Thank you. I'll Close as completed
